# mkdocs, version 1.0.4
site_name: luxe engine
nav:
    - about: index.md
    - install: get.md
    - guide: 
      - intro : guide.md
      - workflow : guide/workflow.md
      - launcher: guide/launcher.md
      - concepts : guide/concepts.md
      - wren primer : guide/wren-primer.md
    - tutorial:
      - overview and goals : tutorial/overview.md
      - creating a project : tutorial/create-and-run-a-project.md
      - display a sprite : tutorial/display-a-sprite.md
      - create a scene : tutorial/create-a-scene.md
      - input handling : tutorial/input-handling.md
      - sprite animation : tutorial/sprite-animation.md
      - camera follow : tutorial/camera-follow.md
      - scene scripts : tutorial/scene-scripts.md 
      - curve animation : tutorial/curve-animation.md
      - create a prototype : tutorial/create-a-prototype.md
      - using modules : tutorial/using-modules.md
      - collision callbacks : tutorial/collision-callbacks.md
      - transform link : tutorial/transform-link.md
      - animation events : tutorial/animation-events.md
      - scheduled functions : tutorial/scheduled-functions.md
      - fading in & out : tutorial/fading-out.md
    - learn ...:
      - overview: learn/overview.md
      - tilemaps : learn/tilemaps.md
      - 2D drawing : learn/drawing-2d.md
      - modifiers:
        - luxe modifiers : learn/modifiers/luxe-modifiers.md
        - custom modifiers : learn/modifiers/custom-modifiers.md
      - using UI:
        - overview : learn/ui/intro.md
        - custom controls : learn/ui/custom-controls.md
        - basic layout : learn/ui/basic-layout.md      
      - random numbers : learn/random-numbers.md
      - multiple wren files : learn/multiple-wren-files.md
      - using modules : learn/modules.md
    - manual: 
      - overview: manual/overview.md
      - runtime:
        - overview: manual/runtime/overview.md
      - asset pipeline:
        - overview: manual/assets/overview.md
      - rendering:
        - overview: manual/rendering/overview.md
        - concepts: manual/rendering/concepts.md
        - high level: manual/rendering/high-level.md
        - low level: manual/rendering/low-level.md
    - release notes:
      - engine : release-notes/engine.md
      - editor : release-notes/editor.md
      - launcher : release-notes/launcher.md
      - agent : release-notes/agent.md
    - modules:
      - overview : modules.md
      - arcade : modules/arcade/api.md
      - tktween : modules/tktween/api.md
    - API: api.md
theme:
  name: material
  custom_dir: overrides
  favicon: images/luxe-favicon.png
  language: 'en'  
  logo: 'images/logo.svg'
  font:
    text: Roboto
    code: Roboto Mono
  palette:
    - scheme: default
      primary: 'pink'
      accent: 'light blue'
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: 'pink'
      accent: 'light blue'
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - instant
extra_css:
  - css/extra.css
markdown_extensions:
  - admonition
  - toc:
      permalink: True
  - footnotes
  - meta
  - markdown.extensions.attr_list
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.highlight:
      linenums_style: pymdownx-inline
  - pymdownx.tasklist:
      custom_checkbox: True
  - pymdownx.tilde
extra:
  social:
    - icon: 'octicons/mark-github-16'
      link: 'https://github.com/luxeengine'
    - icon: 'fontawesome/brands/twitter'
      link: 'https://twitter.com/luxeengine'
use_directory_urls: true
plugins:
  - search:
      prebuild_index: true
      min_search_length: 2
  - exclude:
      glob:
        - usage.md
        # - api.md
        # - api/**