name: build docs

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.9' 
        cache: 'pip'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Build docs
      run: mkdocs build
    - name: Deploy docs
      uses: cpina/github-action-push-to-another-repository@1.7.2
      env:
        SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
      with:
        source-directory: 'site'
        destination-github-username: 'luxeengine'
        destination-repository-name: 'luxeengine.github.io'
        user-email: docs@createwith.luxe
        target-branch: main
    
